from . import license
from . import res_company
from . import res_company_ldap
from . import res_config_settings
from . import res_ldap_group
from . import res_ldap_odoo_mapping
from . import res_ldap_ou
from . import res_odoo_ldap_mapping
from . import res_users